## Matrix Math and numpy 

In [2]:
import pandas as pd 
import tensorflow as tf
import numpy as np


Recuerde que todo se puede representar numericamente , por ejemplo una imagen sis e descompone en pixeles , se puede tabluar en RBG (255,84,131).

Los valores indivuales se les conoce como escalares, ya que tienen cero dimensiones

In [4]:
row_vector = np.array([1,2,3])
row_vector


array([1, 2, 3])

In [9]:
column_vector = np.array([1,2,3])
column_vector.shape=(1,3)
column_vector.transpose()

array([[1],
       [2],
       [3]])

Los vectores anteriores son de una sola dimension

In [10]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m.shape

(3, 3)

In [11]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [12]:
t.shape

(3, 3, 2, 1)

In [13]:
v = np.array([1,2,3,4])
v


array([1, 2, 3, 4])

In [14]:
## Reshape
x = v.reshape(1,4)
x


array([[1, 2, 3, 4]])

In [15]:
x = v[None, :]
x


array([[1, 2, 3, 4]])

## Matrix

In [20]:
import time 
tic = time.time()
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
toc = time.time()
print("For loop "+str(1000*(toc-tic))+"ms")

For loop 0.080108642578125ms


In [21]:
tic = time.time()
values = [1,2,3,4,5]
values = np.array(values) + 5
toc = time.time()
print("For loop "+str(1000*(toc-tic))+"ms")

For loop 0.06604194641113281ms


In [22]:
m = np.array([[1,2,3],[4,5,6]])
n = m * 0.25
n


array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [23]:
m*n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [26]:
np.dot(m,n.T)

array([[ 3.5 ,  8.  ],
       [ 8.  , 19.25]])

In [27]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [28]:
print(a.shape)
print(b.shape)

(2, 4)
(4, 3)


In [31]:
%time
c = np.matmul(a, b)
c

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 2.86 µs


array([[ 70,  80,  90],
       [158, 184, 210]])

In [33]:
%time
np.dot(a,b)

CPU times: user 1 µs, sys: 1 µs, total: 2 µs
Wall time: 3.1 µs


array([[ 70,  80,  90],
       [158, 184, 210]])

In [34]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [35]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

## Quiz